"""Static SEC Standard Industrial Classification (SIC) code catalog.

Generated from the SEC Division of Corporation Finance SIC code list
(sec.gov/corpfin/division-of-corporation-finance-standard-industrial-classification-sic-code-list).
Each entry is one (sic, industry, office) row. The sic_search fetcher filters
this list in-process by substring match - no Sugra endpoint backs SIC lookup.

Snapshot: 2026-06-27 (444 codes). The SEC occasionally revises office
assignments, so regenerate this file from the live list if a stale office name
surfaces; the (sic, industry) pairs are stable.
"""

from __future__ import annotations

SIC_CODES: list[dict] = [
    {"sic": 100, "industry": "AGRICULTURAL PRODUCTION-CROPS", "office": "Industrial Applications and Services"},
    {"sic": 200, "industry": "AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES", "office": "Industrial Applications and Services"},
    {"sic": 700, "industry": "AGRICULTURAL SERVICES", "office": "Industrial Applications and Services"},
    {"sic": 800, "industry": "FORESTRY", "office": "Industrial Applications and Services"},
    {"sic": 900, "industry": "FISHING, HUNTING AND TRAPPING", "office": "Industrial Applications and Services"},
    {"sic": 1000, "industry": "METAL MINING", "office": "Office of Energy & Transportation"},
    {"sic": 1040, "industry": "GOLD AND SILVER ORES", "office": "Office of Energy & Transportation"},
    {"sic": 1090, "industry": "MISCELLANEOUS METAL ORES", "office": "Office of Energy & Transportation"},
    {"sic": 1220, "industry": "BITUMINOUS COAL & LIGNITE MINING", "office": "Office of Energy & Transportation"},
    {"sic": 1221, "industry": "BITUMINOUS COAL & LIGNITE SURFACE MINING", "office": "Office of Energy & Transportation"},
    {"sic": 1311, "industry": "CRUDE PETROLEUM & NATURAL GAS", "office": "Office of Energy & Transportation"},
    {"sic": 1381, "industry": "DRILLING OIL & GAS WELLS", "office": "Office of Energy & Transportation"},
    {"sic": 1382, "industry": "OIL & GAS FIELD EXPLORATION SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 1389, "industry": "OIL & GAS FIELD SERVICES, NEC", "office": "Office of Energy & Transportation"},
    {"sic": 1400, "industry": "MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)", "office": "Office of Energy & Transportation"},
    {"sic": 1520, "industry": "GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS", "office": "Office of Real Estate & Construction"},
    {"sic": 1531, "industry": "OPERATIVE BUILDERS", "office": "Office of Real Estate & Construction"},
    {"sic": 1540, "industry": "GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS", "office": "Office of Real Estate & Construction"},
    {"sic": 1600, "industry": "HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS", "office": "Office of Real Estate & Construction"},
    {"sic": 1623, "industry": "WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION", "office": "Office of Real Estate & Construction"},
    {"sic": 1700, "industry": "CONSTRUCTION - SPECIAL TRADE CONTRACTORS", "office": "Office of Real Estate & Construction"},
    {"sic": 1731, "industry": "ELECTRICAL WORK", "office": "Office of Real Estate & Construction"},
    {"sic": 2000, "industry": "FOOD AND KINDRED PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2011, "industry": "MEAT PACKING PLANTS", "office": "Office of Manufacturing"},
    {"sic": 2013, "industry": "SAUSAGES & OTHER PREPARED MEAT PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2015, "industry": "POULTRY SLAUGHTERING AND PROCESSING", "office": "Office of Manufacturing"},
    {"sic": 2020, "industry": "DAIRY PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2024, "industry": "ICE CREAM & FROZEN DESSERTS", "office": "Office of Manufacturing"},
    {"sic": 2030, "industry": "CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES", "office": "Office of Manufacturing"},
    {"sic": 2033, "industry": "CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES", "office": "Office of Manufacturing"},
    {"sic": 2040, "industry": "GRAIN MILL PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2050, "industry": "BAKERY PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2052, "industry": "COOKIES & CRACKERS", "office": "Office of Manufacturing"},
    {"sic": 2060, "industry": "SUGAR & CONFECTIONERY PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2070, "industry": "FATS & OILS", "office": "Office of Manufacturing"},
    {"sic": 2080, "industry": "BEVERAGES", "office": "Office of Manufacturing"},
    {"sic": 2082, "industry": "MALT BEVERAGES", "office": "Office of Manufacturing"},
    {"sic": 2086, "industry": "BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS", "office": "Office of Manufacturing"},
    {"sic": 2090, "industry": "MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2092, "industry": "PREPARED FRESH OR FROZEN FISH & SEAFOODS", "office": "Office of Manufacturing"},
    {"sic": 2100, "industry": "TOBACCO PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2111, "industry": "CIGARETTES", "office": "Office of Manufacturing"},
    {"sic": 2200, "industry": "TEXTILE MILL PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2211, "industry": "BROADWOVEN FABRIC MILLS, COTTON", "office": "Office of Manufacturing"},
    {"sic": 2221, "industry": "BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK", "office": "Office of Manufacturing"},
    {"sic": 2250, "industry": "KNITTING MILLS", "office": "Office of Manufacturing"},
    {"sic": 2253, "industry": "KNIT OUTERWEAR MILLS", "office": "Office of Manufacturing"},
    {"sic": 2273, "industry": "CARPETS & RUGS", "office": "Office of Manufacturing"},
    {"sic": 2300, "industry": "APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL", "office": "Office of Manufacturing"},
    {"sic": 2320, "industry": "MEN'S & BOYS' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS", "office": "Office of Manufacturing"},
    {"sic": 2330, "industry": "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR", "office": "Office of Manufacturing"},
    {"sic": 2340, "industry": "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS", "office": "Office of Manufacturing"},
    {"sic": 2390, "industry": "MISCELLANEOUS FABRICATED TEXTILE PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2400, "industry": "LUMBER & WOOD PRODUCTS (NO FURNITURE)", "office": "Office of Manufacturing"},
    {"sic": 2421, "industry": "SAWMILLS & PLANTING MILLS, GENERAL", "office": "Office of Manufacturing"},
    {"sic": 2430, "industry": "MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS", "office": "Office of Manufacturing"},
    {"sic": 2451, "industry": "MOBILE HOMES", "office": "Office of Manufacturing"},
    {"sic": 2452, "industry": "PREFABRICATED WOOD BLDGS & COMPONENTS", "office": "Office of Manufacturing"},
    {"sic": 2510, "industry": "HOUSEHOLD FURNITURE", "office": "Office of Manufacturing"},
    {"sic": 2511, "industry": "WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)", "office": "Office of Manufacturing"},
    {"sic": 2520, "industry": "OFFICE FURNITURE", "office": "Office of Manufacturing"},
    {"sic": 2522, "industry": "OFFICE FURNITURE (NO WOOD)", "office": "Office of Manufacturing"},
    {"sic": 2531, "industry": "PUBLIC BLDG & RELATED FURNITURE", "office": "Office of Manufacturing"},
    {"sic": 2540, "industry": "PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES", "office": "Office of Manufacturing"},
    {"sic": 2590, "industry": "MISCELLANEOUS FURNITURE & FIXTURES", "office": "Office of Manufacturing"},
    {"sic": 2600, "industry": "PAPERS & ALLIED PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 2611, "industry": "PULP MILLS", "office": "Office of Manufacturing"},
    {"sic": 2621, "industry": "PAPER MILLS", "office": "Office of Manufacturing"},
    {"sic": 2631, "industry": "PAPERBOARD MILLS", "office": "Office of Manufacturing"},
    {"sic": 2650, "industry": "PAPERBOARD CONTAINERS & BOXES", "office": "Office of Manufacturing"},
    {"sic": 2670, "industry": "CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)", "office": "Office of Manufacturing"},
    {"sic": 2673, "industry": "PLASTICS, FOIL & COATED PAPER BAGS", "office": "Office of Manufacturing"},
    {"sic": 2711, "industry": "NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING", "office": "Office of Manufacturing"},
    {"sic": 2721, "industry": "PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING", "office": "Office of Manufacturing"},
    {"sic": 2731, "industry": "BOOKS: PUBLISHING OR PUBLISHING & PRINTING", "office": "Office of Manufacturing"},
    {"sic": 2732, "industry": "BOOK PRINTING", "office": "Office of Manufacturing"},
    {"sic": 2741, "industry": "MISCELLANEOUS PUBLISHING", "office": "Office of Manufacturing"},
    {"sic": 2750, "industry": "COMMERCIAL PRINTING", "office": "Office of Manufacturing"},
    {"sic": 2761, "industry": "MANIFOLD BUSINESS FORMS", "office": "Office of Manufacturing"},
    {"sic": 2771, "industry": "GREETING CARDS", "office": "Office of Manufacturing"},
    {"sic": 2780, "industry": "BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK", "office": "Office of Manufacturing"},
    {"sic": 2790, "industry": "SERVICE INDUSTRIES FOR THE PRINTING TRADE", "office": "Office of Manufacturing"},
    {"sic": 2800, "industry": "CHEMICALS & ALLIED PRODUCTS", "office": "Industrial Applications and Services"},
    {"sic": 2810, "industry": "INDUSTRIAL INORGANIC CHEMICALS", "office": "Industrial Applications and Services"},
    {"sic": 2820, "industry": "PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)", "office": "Industrial Applications and Services"},
    {"sic": 2821, "industry": "PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS", "office": "Industrial Applications and Services"},
    {"sic": 2833, "industry": "MEDICINAL CHEMICALS & BOTANICAL PRODUCTS", "office": "Office of Life Sciences"},
    {"sic": 2834, "industry": "PHARMACEUTICAL PREPARATIONS", "office": "Office of Life Sciences"},
    {"sic": 2835, "industry": "IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES", "office": "Office of Life Sciences"},
    {"sic": 2836, "industry": "BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)", "office": "Office of Life Sciences"},
    {"sic": 2840, "industry": "SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS", "office": "Industrial Applications and Services"},
    {"sic": 2842, "industry": "SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS", "office": "Industrial Applications and Services"},
    {"sic": 2844, "industry": "PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS", "office": "Industrial Applications and Services"},
    {"sic": 2851, "industry": "PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS", "office": "Industrial Applications and Services"},
    {"sic": 2860, "industry": "INDUSTRIAL ORGANIC CHEMICALS", "office": "Industrial Applications and Services"},
    {"sic": 2870, "industry": "AGRICULTURAL CHEMICALS", "office": "Industrial Applications and Services"},
    {"sic": 2890, "industry": "MISCELLANEOUS CHEMICAL PRODUCTS", "office": "Industrial Applications and Services"},
    {"sic": 2891, "industry": "ADHESIVES & SEALANTS", "office": "Industrial Applications and Services"},
    {"sic": 2911, "industry": "PETROLEUM REFINING", "office": "Office of Energy & Transportation"},
    {"sic": 2950, "industry": "ASPHALT PAVING & ROOFING MATERIALS", "office": "Office of Energy & Transportation"},
    {"sic": 2990, "industry": "MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL", "office": "Office of Energy & Transportation"},
    {"sic": 3011, "industry": "TIRES & INNER TUBES", "office": "Office of Manufacturing"},
    {"sic": 3021, "industry": "RUBBER & PLASTICS FOOTWEAR", "office": "Office of Manufacturing"},
    {"sic": 3050, "industry": "GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE", "office": "Office of Manufacturing"},
    {"sic": 3060, "industry": "FABRICATED RUBBER PRODUCTS, NEC", "office": "Office of Manufacturing"},
    {"sic": 3080, "industry": "MISCELLANEOUS PLASTICS PRODUCTS", "office": "Industrial Applications and Services"},
    {"sic": 3081, "industry": "UNSUPPORTED PLASTICS FILM & SHEET", "office": "Industrial Applications and Services"},
    {"sic": 3086, "industry": "PLASTICS FOAM PRODUCTS", "office": "Industrial Applications and Services"},
    {"sic": 3089, "industry": "PLASTICS PRODUCTS, NEC", "office": "Industrial Applications and Services"},
    {"sic": 3100, "industry": "LEATHER & LEATHER PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3140, "industry": "FOOTWEAR, (NO RUBBER)", "office": "Office of Manufacturing"},
    {"sic": 3211, "industry": "FLAT GLASS", "office": "Office of Manufacturing"},
    {"sic": 3220, "industry": "GLASS & GLASSWARE, PRESSED OR BLOWN", "office": "Office of Manufacturing"},
    {"sic": 3221, "industry": "GLASS CONTAINERS", "office": "Office of Manufacturing"},
    {"sic": 3231, "industry": "GLASS PRODUCTS, MADE OF PURCHASED GLASS", "office": "Office of Manufacturing"},
    {"sic": 3241, "industry": "CEMENT, HYDRAULIC", "office": "Office of Manufacturing"},
    {"sic": 3250, "industry": "STRUCTURAL CLAY PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3260, "industry": "POTTERY & RELATED PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3270, "industry": "CONCRETE, GYPSUM & PLASTER PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3272, "industry": "CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK", "office": "Office of Manufacturing"},
    {"sic": 3281, "industry": "CUT STONE & STONE PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3290, "industry": "ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS", "office": "Office of Manufacturing"},
    {"sic": 3310, "industry": "STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS", "office": "Office of Manufacturing"},
    {"sic": 3312, "industry": "STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)", "office": "Office of Manufacturing"},
    {"sic": 3317, "industry": "STEEL PIPE & TUBES", "office": "Office of Manufacturing"},
    {"sic": 3320, "industry": "IRON & STEEL FOUNDRIES", "office": "Office of Manufacturing"},
    {"sic": 3330, "industry": "PRIMARY SMELTING & REFINING OF NONFERROUS METALS", "office": "Office of Manufacturing"},
    {"sic": 3334, "industry": "PRIMARY PRODUCTION OF ALUMINUM", "office": "Office of Manufacturing"},
    {"sic": 3341, "industry": "SECONDARY SMELTING & REFINING OF NONFERROUS METALS", "office": "Office of Manufacturing"},
    {"sic": 3350, "industry": "ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS", "office": "Office of Manufacturing"},
    {"sic": 3357, "industry": "DRAWING & INSULATING OF NONFERROUS WIRE", "office": "Office of Manufacturing"},
    {"sic": 3360, "industry": "NONFERROUS FOUNDRIES (CASTINGS)", "office": "Office of Manufacturing"},
    {"sic": 3390, "industry": "MISCELLANEOUS PRIMARY METAL PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3411, "industry": "METAL CANS", "office": "Office of Manufacturing"},
    {"sic": 3412, "industry": "METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS", "office": "Office of Manufacturing"},
    {"sic": 3420, "industry": "CUTLERY, HANDTOOLS & GENERAL HARDWARE", "office": "Office of Manufacturing"},
    {"sic": 3430, "industry": "HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES", "office": "Office of Manufacturing"},
    {"sic": 3433, "industry": "HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES", "office": "Office of Manufacturing"},
    {"sic": 3440, "industry": "FABRICATED STRUCTURAL METAL PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3442, "industry": "METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM", "office": "Office of Manufacturing"},
    {"sic": 3443, "industry": "FABRICATED PLATE WORK (BOILER SHOPS)", "office": "Office of Manufacturing"},
    {"sic": 3444, "industry": "SHEET METAL WORK", "office": "Office of Manufacturing"},
    {"sic": 3448, "industry": "PREFABRICATED METAL BUILDINGS & COMPONENTS", "office": "Office of Manufacturing"},
    {"sic": 3451, "industry": "SCREW MACHINE PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3452, "industry": "BOLTS, NUTS, SCREWS, RIVETS & WASHERS", "office": "Office of Manufacturing"},
    {"sic": 3460, "industry": "METAL FORGINGS & STAMPINGS", "office": "Office of Manufacturing"},
    {"sic": 3470, "industry": "COATING, ENGRAVING & ALLIED SERVICES", "office": "Office of Manufacturing"},
    {"sic": 3480, "industry": "ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)", "office": "Office of Manufacturing"},
    {"sic": 3490, "industry": "MISCELLANEOUS FABRICATED METAL PRODUCTS", "office": "Office of Manufacturing"},
    {"sic": 3510, "industry": "ENGINES & TURBINES", "office": "Office of Technology"},
    {"sic": 3523, "industry": "FARM MACHINERY & EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3524, "industry": "LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP", "office": "Office of Technology"},
    {"sic": 3530, "industry": "CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP", "office": "Office of Technology"},
    {"sic": 3531, "industry": "CONSTRUCTION MACHINERY & EQUIP", "office": "Office of Technology"},
    {"sic": 3532, "industry": "MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)", "office": "Office of Technology"},
    {"sic": 3533, "industry": "OIL & GAS FIELD MACHINERY & EQUIPMENT", "office": "Office of Energy & Transportation"},
    {"sic": 3537, "industry": "INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS", "office": "Office of Technology"},
    {"sic": 3540, "industry": "METALWORKG MACHINERY & EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3541, "industry": "MACHINE TOOLS, METAL CUTTING TYPES", "office": "Office of Technology"},
    {"sic": 3550, "industry": "SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)", "office": "Office of Technology"},
    {"sic": 3555, "industry": "PRINTING TRADES MACHINERY & EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3559, "industry": "SPECIAL INDUSTRY MACHINERY, NEC", "office": "Office of Technology"},
    {"sic": 3560, "industry": "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3561, "industry": "PUMPS & PUMPING EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3562, "industry": "BALL & ROLLER BEARINGS", "office": "Office of Technology"},
    {"sic": 3564, "industry": "INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP", "office": "Office of Technology"},
    {"sic": 3567, "industry": "INDUSTRIAL PROCESS FURNACES & OVENS", "office": "Office of Technology"},
    {"sic": 3569, "industry": "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC", "office": "Office of Technology"},
    {"sic": 3570, "industry": "COMPUTER & OFFICE EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3571, "industry": "ELECTRONIC COMPUTERS", "office": "Office of Technology"},
    {"sic": 3572, "industry": "COMPUTER STORAGE DEVICES", "office": "Office of Technology"},
    {"sic": 3575, "industry": "COMPUTER TERMINALS", "office": "Office of Technology"},
    {"sic": 3576, "industry": "COMPUTER COMMUNICATIONS EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3577, "industry": "COMPUTER PERIPHERAL EQUIPMENT, NEC", "office": "Office of Technology"},
    {"sic": 3578, "industry": "CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)", "office": "Office of Technology"},
    {"sic": 3579, "industry": "OFFICE MACHINES, NEC", "office": "Office of Technology"},
    {"sic": 3580, "industry": "REFRIGERATION & SERVICE INDUSTRY MACHINERY", "office": "Office of Technology"},
    {"sic": 3585, "industry": "AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP", "office": "Office of Technology"},
    {"sic": 3590, "industry": "MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT", "office": "Office of Technology"},
    {"sic": 3600, "industry": "ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)", "office": "Office of Manufacturing"},
    {"sic": 3612, "industry": "POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS", "office": "Office of Manufacturing"},
    {"sic": 3613, "industry": "SWITCHGEAR & SWITCHBOARD APPARATUS", "office": "Office of Manufacturing"},
    {"sic": 3620, "industry": "ELECTRICAL INDUSTRIAL APPARATUS", "office": "Office of Manufacturing"},
    {"sic": 3621, "industry": "MOTORS & GENERATORS", "office": "Office of Manufacturing"},
    {"sic": 3630, "industry": "HOUSEHOLD APPLIANCES", "office": "Office of Manufacturing"},
    {"sic": 3634, "industry": "ELECTRIC HOUSEWARES & FANS", "office": "Office of Manufacturing"},
    {"sic": 3640, "industry": "ELECTRIC LIGHTING & WIRING EQUIPMENT", "office": "Office of Manufacturing"},
    {"sic": 3651, "industry": "HOUSEHOLD AUDIO & VIDEO EQUIPMENT", "office": "Office of Manufacturing"},
    {"sic": 3652, "industry": "PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS", "office": "Office of Manufacturing"},
    {"sic": 3661, "industry": "TELEPHONE & TELEGRAPH APPARATUS", "office": "Office of Manufacturing"},
    {"sic": 3663, "industry": "RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT", "office": "Office of Manufacturing"},
    {"sic": 3669, "industry": "COMMUNICATIONS EQUIPMENT, NEC", "office": "Office of Manufacturing"},
    {"sic": 3670, "industry": "ELECTRONIC COMPONENTS & ACCESSORIES", "office": "Office of Manufacturing"},
    {"sic": 3672, "industry": "PRINTED CIRCUIT BOARDS", "office": "Office of Manufacturing"},
    {"sic": 3674, "industry": "SEMICONDUCTORS & RELATED DEVICES", "office": "Office of Manufacturing"},
    {"sic": 3677, "industry": "ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS", "office": "Office of Manufacturing"},
    {"sic": 3678, "industry": "ELECTRONIC CONNECTORS", "office": "Office of Manufacturing"},
    {"sic": 3679, "industry": "ELECTRONIC COMPONENTS, NEC", "office": "Office of Manufacturing"},
    {"sic": 3690, "industry": "MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES", "office": "Office of Manufacturing"},
    {"sic": 3695, "industry": "MAGNETIC & OPTICAL RECORDING MEDIA", "office": "Office of Manufacturing"},
    {"sic": 3711, "industry": "MOTOR VEHICLES & PASSENGER CAR BODIES", "office": "Office of Manufacturing"},
    {"sic": 3713, "industry": "TRUCK & BUS BODIES", "office": "Office of Manufacturing"},
    {"sic": 3714, "industry": "MOTOR VEHICLE PARTS & ACCESSORIES", "office": "Office of Manufacturing"},
    {"sic": 3715, "industry": "TRUCK TRAILERS", "office": "Office of Manufacturing"},
    {"sic": 3716, "industry": "MOTOR HOMES", "office": "Office of Manufacturing"},
    {"sic": 3720, "industry": "AIRCRAFT & PARTS", "office": "Office of Manufacturing"},
    {"sic": 3721, "industry": "AIRCRAFT", "office": "Office of Manufacturing"},
    {"sic": 3724, "industry": "AIRCRAFT ENGINES & ENGINE PARTS", "office": "Office of Manufacturing"},
    {"sic": 3728, "industry": "AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC", "office": "Office of Manufacturing"},
    {"sic": 3730, "industry": "SHIP & BOAT BUILDING & REPAIRING", "office": "Office of Manufacturing"},
    {"sic": 3743, "industry": "RAILROAD EQUIPMENT", "office": "Office of Manufacturing"},
    {"sic": 3751, "industry": "MOTORCYCLES, BICYCLES & PARTS", "office": "Office of Manufacturing"},
    {"sic": 3760, "industry": "GUIDED MISSILES & SPACE VEHICLES & PARTS", "office": "Office of Manufacturing"},
    {"sic": 3790, "industry": "MISCELLANEOUS TRANSPORTATION EQUIPMENT", "office": "Office of Manufacturing"},
    {"sic": 3812, "industry": "SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS", "office": "Office of Manufacturing"},
    {"sic": 3821, "industry": "LABORATORY APPARATUS & FURNITURE", "office": "Industrial Applications and Services"},
    {"sic": 3822, "industry": "AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS", "office": "Industrial Applications and Services"},
    {"sic": 3823, "industry": "INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL", "office": "Industrial Applications and Services"},
    {"sic": 3824, "industry": "TOTALIZING FLUID METERS & COUNTING DEVICES", "office": "Industrial Applications and Services"},
    {"sic": 3825, "industry": "INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS", "office": "Industrial Applications and Services"},
    {"sic": 3826, "industry": "LABORATORY ANALYTICAL INSTRUMENTS", "office": "Industrial Applications and Services"},
    {"sic": 3827, "industry": "OPTICAL INSTRUMENTS & LENSES", "office": "Industrial Applications and Services"},
    {"sic": 3829, "industry": "MEASURING & CONTROLLING DEVICES, NEC", "office": "Industrial Applications and Services"},
    {"sic": 3841, "industry": "SURGICAL & MEDICAL INSTRUMENTS & APPARATUS", "office": "Industrial Applications and Services"},
    {"sic": 3842, "industry": "ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES", "office": "Industrial Applications and Services"},
    {"sic": 3843, "industry": "DENTAL EQUIPMENT & SUPPLIES", "office": "Industrial Applications and Services"},
    {"sic": 3844, "industry": "X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS", "office": "Industrial Applications and Services"},
    {"sic": 3845, "industry": "ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS", "office": "Industrial Applications and Services"},
    {"sic": 3851, "industry": "OPHTHALMIC GOODS", "office": "Industrial Applications and Services"},
    {"sic": 3861, "industry": "PHOTOGRAPHIC EQUIPMENT & SUPPLIES", "office": "Industrial Applications and Services"},
    {"sic": 3873, "industry": "WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS", "office": "Industrial Applications and Services"},
    {"sic": 3910, "industry": "JEWELRY, SILVERWARE & PLATED WARE", "office": "Office of Manufacturing"},
    {"sic": 3911, "industry": "JEWELRY, PRECIOUS METAL", "office": "Office of Manufacturing"},
    {"sic": 3931, "industry": "MUSICAL INSTRUMENTS", "office": "Office of Manufacturing"},
    {"sic": 3942, "industry": "DOLLS & STUFFED TOYS", "office": "Office of Manufacturing"},
    {"sic": 3944, "industry": "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES)", "office": "Office of Manufacturing"},
    {"sic": 3949, "industry": "SPORTING & ATHLETIC GOODS, NEC", "office": "Office of Manufacturing"},
    {"sic": 3950, "industry": "PENS, PENCILS & OTHER ARTISTS' MATERIALS", "office": "Office of Manufacturing"},
    {"sic": 3960, "industry": "COSTUME JEWELRY & NOVELTIES", "office": "Office of Manufacturing"},
    {"sic": 3990, "industry": "MISCELLANEOUS MANUFACTURING INDUSTRIES", "office": "Office of Manufacturing"},
    {"sic": 4011, "industry": "RAILROADS, LINE-HAUL OPERATING", "office": "Office of Energy & Transportation"},
    {"sic": 4013, "industry": "RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS", "office": "Office of Energy & Transportation"},
    {"sic": 4100, "industry": "LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS", "office": "Office of Energy & Transportation"},
    {"sic": 4210, "industry": "TRUCKING & COURIER SERVICES (NO AIR)", "office": "Office of Energy & Transportation"},
    {"sic": 4213, "industry": "TRUCKING (NO LOCAL)", "office": "Office of Energy & Transportation"},
    {"sic": 4220, "industry": "PUBLIC WAREHOUSING & STORAGE", "office": "Office of Energy & Transportation"},
    {"sic": 4231, "industry": "TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT", "office": "Office of Energy & Transportation"},
    {"sic": 4400, "industry": "WATER TRANSPORTATION", "office": "Office of Energy & Transportation"},
    {"sic": 4412, "industry": "DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT", "office": "Office of Energy & Transportation"},
    {"sic": 4512, "industry": "AIR TRANSPORTATION, SCHEDULED", "office": "Office of Energy & Transportation"},
    {"sic": 4513, "industry": "AIR COURIER SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 4522, "industry": "AIR TRANSPORTATION, NONSCHEDULED", "office": "Office of Energy & Transportation"},
    {"sic": 4581, "industry": "AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 4610, "industry": "PIPE LINES (NO NATURAL GAS)", "office": "Office of Energy & Transportation"},
    {"sic": 4700, "industry": "TRANSPORTATION SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 4731, "industry": "ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO", "office": "Office of Energy & Transportation"},
    {"sic": 4812, "industry": "RADIOTELEPHONE COMMUNICATIONS", "office": "Office of Technology"},
    {"sic": 4813, "industry": "TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)", "office": "Office of Technology"},
    {"sic": 4822, "industry": "TELEGRAPH & OTHER MESSAGE COMMUNICATIONS", "office": "Office of Technology"},
    {"sic": 4832, "industry": "RADIO BROADCASTING STATIONS", "office": "Office of Technology"},
    {"sic": 4833, "industry": "TELEVISION BROADCASTING STATIONS", "office": "Office of Technology"},
    {"sic": 4841, "industry": "CABLE & OTHER PAY TELEVISION SERVICES", "office": "Office of Technology"},
    {"sic": 4899, "industry": "COMMUNICATIONS SERVICES, NEC", "office": "Office of Technology"},
    {"sic": 4900, "industry": "ELECTRIC, GAS & SANITARY SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 4911, "industry": "ELECTRIC SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 4922, "industry": "NATURAL GAS TRANSMISSION", "office": "Office of Energy & Transportation"},
    {"sic": 4923, "industry": "NATURAL GAS TRANSMISISON & DISTRIBUTION", "office": "Office of Energy & Transportation"},
    {"sic": 4924, "industry": "NATURAL GAS DISTRIBUTION", "office": "Office of Energy & Transportation"},
    {"sic": 4931, "industry": "ELECTRIC & OTHER SERVICES COMBINED", "office": "Office of Energy & Transportation"},
    {"sic": 4932, "industry": "GAS & OTHER SERVICES COMBINED", "office": "Office of Energy & Transportation"},
    {"sic": 4941, "industry": "WATER SUPPLY", "office": "Office of Energy & Transportation"},
    {"sic": 4950, "industry": "SANITARY SERVICES", "office": "Office of Energy & Transportation"},
    {"sic": 4953, "industry": "REFUSE SYSTEMS", "office": "Office of Energy & Transportation"},
    {"sic": 4955, "industry": "HAZARDOUS WASTE MANAGEMENT", "office": "Office of Energy & Transportation"},
    {"sic": 4961, "industry": "STEAM & AIR-CONDITIONING SUPPLY", "office": "Office of Energy & Transportation"},
    {"sic": 4991, "industry": "COGENERATION SERVICES & SMALL POWER PRODUCERS", "office": "Office of Energy & Transportation"},
    {"sic": 5000, "industry": "WHOLESALE-DURABLE GOODS", "office": "Office of Trade & Services"},
    {"sic": 5010, "industry": "WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES", "office": "Office of Trade & Services"},
    {"sic": 5013, "industry": "WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS", "office": "Office of Trade & Services"},
    {"sic": 5020, "industry": "WHOLESALE-FURNITURE & HOME FURNISHINGS", "office": "Office of Trade & Services"},
    {"sic": 5030, "industry": "WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS", "office": "Office of Trade & Services"},
    {"sic": 5031, "industry": "WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS", "office": "Office of Trade & Services"},
    {"sic": 5040, "industry": "WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES", "office": "Office of Trade & Services"},
    {"sic": 5045, "industry": "WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE", "office": "Office of Trade & Services"},
    {"sic": 5047, "industry": "WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES", "office": "Office of Trade & Services"},
    {"sic": 5050, "industry": "WHOLESALE-METALS & MINERALS (NO PETROLEUM)", "office": "Office of Trade & Services"},
    {"sic": 5051, "industry": "WHOLESALE-METALS SERVICE CENTERS & OFFICES", "office": "Office of Trade & Services"},
    {"sic": 5063, "industry": "WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES", "office": "Office of Trade & Services"},
    {"sic": 5064, "industry": "WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS", "office": "Office of Trade & Services"},
    {"sic": 5065, "industry": "WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC", "office": "Office of Trade & Services"},
    {"sic": 5070, "industry": "WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES", "office": "Office of Trade & Services"},
    {"sic": 5072, "industry": "WHOLESALE-HARDWARE", "office": "Office of Trade & Services"},
    {"sic": 5080, "industry": "WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES", "office": "Office of Trade & Services"},
    {"sic": 5082, "industry": "WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP", "office": "Office of Trade & Services"},
    {"sic": 5084, "industry": "WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT", "office": "Office of Trade & Services"},
    {"sic": 5090, "industry": "WHOLESALE-MISC DURABLE GOODS", "office": "Office of Trade & Services"},
    {"sic": 5094, "industry": "WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS", "office": "Office of Trade & Services"},
    {"sic": 5099, "industry": "WHOLESALE-DURABLE GOODS, NEC", "office": "Office of Trade & Services"},
    {"sic": 5110, "industry": "WHOLESALE-PAPER & PAPER PRODUCTS", "office": "Office of Trade & Services"},
    {"sic": 5122, "industry": "WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS' SUNDRIES", "office": "Office of Trade & Services"},
    {"sic": 5130, "industry": "WHOLESALE-APPAREL, PIECE GOODS & NOTIONS", "office": "Office of Trade & Services"},
    {"sic": 5140, "industry": "WHOLESALE-GROCERIES & RELATED PRODUCTS", "office": "Office of Trade & Services"},
    {"sic": 5141, "industry": "WHOLESALE-GROCERIES, GENERAL LINE", "office": "Office of Trade & Services"},
    {"sic": 5150, "industry": "WHOLESALE-FARM PRODUCT RAW MATERIALS", "office": "Office of Trade & Services"},
    {"sic": 5160, "industry": "WHOLESALE-CHEMICALS & ALLIED PRODUCTS", "office": "Office of Trade & Services"},
    {"sic": 5171, "industry": "WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS", "office": "Office of Trade & Services"},
    {"sic": 5172, "industry": "WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)", "office": "Office of Trade & Services"},
    {"sic": 5180, "industry": "WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES", "office": "Office of Trade & Services"},
    {"sic": 5190, "industry": "WHOLESALE-MISCELLANEOUS NONDURABLE GOODS", "office": "Office of Trade & Services"},
    {"sic": 5200, "industry": "RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY", "office": "Office of Trade & Services"},
    {"sic": 5211, "industry": "RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS", "office": "Office of Trade & Services"},
    {"sic": 5271, "industry": "RETAIL-MOBILE HOME DEALERS", "office": "Office of Trade & Services"},
    {"sic": 5311, "industry": "RETAIL-DEPARTMENT STORES", "office": "Office of Trade & Services"},
    {"sic": 5331, "industry": "RETAIL-VARIETY STORES", "office": "Office of Trade & Services"},
    {"sic": 5399, "industry": "RETAIL-MISC GENERAL MERCHANDISE STORES", "office": "Office of Trade & Services"},
    {"sic": 5400, "industry": "RETAIL-FOOD STORES", "office": "Office of Trade & Services"},
    {"sic": 5411, "industry": "RETAIL-GROCERY STORES", "office": "Office of Trade & Services"},
    {"sic": 5412, "industry": "RETAIL-CONVENIENCE STORES", "office": "Office of Trade & Services"},
    {"sic": 5500, "industry": "RETAIL-AUTO DEALERS & GASOLINE STATIONS", "office": "Office of Trade & Services"},
    {"sic": 5531, "industry": "RETAIL-AUTO & HOME SUPPLY STORES", "office": "Office of Trade & Services"},
    {"sic": 5600, "industry": "RETAIL-APPAREL & ACCESSORY STORES", "office": "Office of Trade & Services"},
    {"sic": 5621, "industry": "RETAIL-WOMEN'S CLOTHING STORES", "office": "Office of Trade & Services"},
    {"sic": 5651, "industry": "RETAIL-FAMILY CLOTHING STORES", "office": "Office of Trade & Services"},
    {"sic": 5661, "industry": "RETAIL-SHOE STORES", "office": "Office of Trade & Services"},
    {"sic": 5700, "industry": "RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES", "office": "Office of Trade & Services"},
    {"sic": 5712, "industry": "RETAIL-FURNITURE STORES", "office": "Office of Trade & Services"},
    {"sic": 5731, "industry": "RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES", "office": "Office of Trade & Services"},
    {"sic": 5734, "industry": "RETAIL-COMPUTER & COMPUTER SOFTWARE STORES", "office": "Office of Trade & Services"},
    {"sic": 5735, "industry": "RETAIL-RECORD & PRERECORDED TAPE STORES", "office": "Office of Trade & Services"},
    {"sic": 5810, "industry": "RETAIL-EATING & DRINKING PLACES", "office": "Office of Trade & Services"},
    {"sic": 5812, "industry": "RETAIL-EATING PLACES", "office": "Office of Trade & Services"},
    {"sic": 5900, "industry": "RETAIL-MISCELLANEOUS RETAIL", "office": "Office of Trade & Services"},
    {"sic": 5912, "industry": "RETAIL-DRUG STORES AND PROPRIETARY STORES", "office": "Office of Trade & Services"},
    {"sic": 5940, "industry": "RETAIL-MISCELLANEOUS SHOPPING GOODS STORES", "office": "Office of Trade & Services"},
    {"sic": 5944, "industry": "RETAIL-JEWELRY STORES", "office": "Office of Trade & Services"},
    {"sic": 5945, "industry": "RETAIL-HOBBY, TOY & GAME SHOPS", "office": "Office of Trade & Services"},
    {"sic": 5960, "industry": "RETAIL-NONSTORE RETAILERS", "office": "Office of Trade & Services"},
    {"sic": 5961, "industry": "RETAIL-CATALOG & MAIL-ORDER HOUSES", "office": "Office of Trade & Services"},
    {"sic": 5990, "industry": "RETAIL-RETAIL STORES, NEC", "office": "Office of Trade & Services"},
    {"sic": 6021, "industry": "NATIONAL COMMERCIAL BANKS", "office": "Office of Finance"},
    {"sic": 6022, "industry": "STATE COMMERCIAL BANKS", "office": "Office of Finance"},
    {"sic": 6029, "industry": "COMMERCIAL BANKS, NEC", "office": "Office of Finance"},
    {"sic": 6035, "industry": "SAVINGS INSTITUTION, FEDERALLY CHARTERED", "office": "Office of Finance"},
    {"sic": 6036, "industry": "SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED", "office": "Office of Finance"},
    {"sic": 6099, "industry": "FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC", "office": "Office of Finance"},
    {"sic": 6111, "industry": "FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES", "office": "Office of Finance"},
    {"sic": 6141, "industry": "PERSONAL CREDIT INSTITUTIONS", "office": "Office of Finance"},
    {"sic": 6153, "industry": "SHORT-TERM BUSINESS CREDIT INSTITUTIONS", "office": "Office of Finance"},
    {"sic": 6159, "industry": "MISCELLANEOUS BUSINESS CREDIT INSTITUTION", "office": "Office of Finance"},
    {"sic": 6162, "industry": "MORTGAGE BANKERS & LOAN CORRESPONDENTS", "office": "Office of Finance"},
    {"sic": 6163, "industry": "LOAN BROKERS", "office": "Office of Finance"},
    {"sic": 6172, "industry": "FINANCE LESSORS", "office": "Office of Finance"},
    {"sic": 6189, "industry": "ASSET-BACKED SECURITIES", "office": "Office of Structured Finance"},
    {"sic": 6199, "industry": "FINANCE SERVICES", "office": "Office of Finance or Office of Crypto Assets"},
    {"sic": 6200, "industry": "SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES", "office": "Office of Crypto Assets"},
    {"sic": 6211, "industry": "SECURITY BROKERS, DEALERS & FLOTATION COMPANIES", "office": "Office of Finance or Office of Crypto Assets"},
    {"sic": 6221, "industry": "COMMODITY CONTRACTS BROKERS & DEALERS", "office": "Office of Crypto Assets"},
    {"sic": 6282, "industry": "INVESTMENT ADVICE", "office": "Office of Finance"},
    {"sic": 6311, "industry": "LIFE INSURANCE", "office": "Office of Finance"},
    {"sic": 6321, "industry": "ACCIDENT & HEALTH INSURANCE", "office": "Office of Finance"},
    {"sic": 6324, "industry": "HOSPITAL & MEDICAL SERVICE PLANS", "office": "Office of Finance"},
    {"sic": 6331, "industry": "FIRE, MARINE & CASUALTY INSURANCE", "office": "Office of Finance"},
    {"sic": 6351, "industry": "SURETY INSURANCE", "office": "Office of Finance"},
    {"sic": 6361, "industry": "TITLE INSURANCE", "office": "Office of Finance"},
    {"sic": 6399, "industry": "INSURANCE CARRIERS, NEC", "office": "Office of Finance"},
    {"sic": 6411, "industry": "INSURANCE AGENTS, BROKERS & SERVICE", "office": "Office of Finance"},
    {"sic": 6500, "industry": "REAL ESTATE", "office": "Office of Real Estate & Construction"},
    {"sic": 6510, "industry": "REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS", "office": "Office of Real Estate & Construction"},
    {"sic": 6512, "industry": "OPERATORS OF NONRESIDENTIAL BUILDINGS", "office": "Office of Real Estate & Construction"},
    {"sic": 6513, "industry": "OPERATORS OF APARTMENT BUILDINGS", "office": "Office of Real Estate & Construction"},
    {"sic": 6519, "industry": "LESSORS OF REAL PROPERTY, NEC", "office": "Office of Real Estate & Construction"},
    {"sic": 6531, "industry": "REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)", "office": "Office of Real Estate & Construction"},
    {"sic": 6532, "industry": "REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)", "office": "Office of Real Estate & Construction"},
    {"sic": 6552, "industry": "LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)", "office": "Office of Real Estate & Construction"},
    {"sic": 6770, "industry": "BLANK CHECKS", "office": "Multiple Offices"},
    {"sic": 6792, "industry": "OIL ROYALTY TRADERS", "office": "Office of Energy & Transportation"},
    {"sic": 6794, "industry": "PATENT OWNERS & LESSORS", "office": "Office of Real Estate & Construction"},
    {"sic": 6795, "industry": "MINERAL ROYALTY TRADERS", "office": "Office of Energy & Transportation"},
    {"sic": 6798, "industry": "REAL ESTATE INVESTMENT TRUSTS", "office": "Office of Real Estate & Construction"},
    {"sic": 6799, "industry": "INVESTORS, NEC", "office": "Office of Real Estate & Construction"},
    {"sic": 7000, "industry": "HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES", "office": "Office of Real Estate & Construction"},
    {"sic": 7011, "industry": "HOTELS & MOTELS", "office": "Office of Real Estate & Construction"},
    {"sic": 7200, "industry": "SERVICES-PERSONAL SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7310, "industry": "SERVICES-ADVERTISING", "office": "Office of Trade & Services"},
    {"sic": 7311, "industry": "SERVICES-ADVERTISING AGENCIES", "office": "Office of Trade & Services"},
    {"sic": 7320, "industry": "SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES", "office": "Office of Trade & Services"},
    {"sic": 7330, "industry": "SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY", "office": "Office of Trade & Services"},
    {"sic": 7331, "industry": "SERVICES-DIRECT MAIL ADVERTISING SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7340, "industry": "SERVICES-TO DWELLINGS & OTHER BUILDINGS", "office": "Office of Trade & Services"},
    {"sic": 7350, "industry": "SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING", "office": "Office of Trade & Services"},
    {"sic": 7359, "industry": "SERVICES-EQUIPMENT RENTAL & LEASING, NEC", "office": "Office of Trade & Services"},
    {"sic": 7361, "industry": "SERVICES-EMPLOYMENT AGENCIES", "office": "Office of Trade & Services"},
    {"sic": 7363, "industry": "SERVICES-HELP SUPPLY SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7370, "industry": "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.", "office": "Office of Technology"},
    {"sic": 7371, "industry": "SERVICES-COMPUTER PROGRAMMING SERVICES", "office": "Office of Technology"},
    {"sic": 7372, "industry": "SERVICES-PREPACKAGED SOFTWARE", "office": "Office of Technology"},
    {"sic": 7373, "industry": "SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN", "office": "Office of Technology"},
    {"sic": 7374, "industry": "SERVICES-COMPUTER PROCESSING & DATA PREPARATION", "office": "Office of Technology"},
    {"sic": 7377, "industry": "SERVICES-COMPUTER RENTAL & LEASING", "office": "Office of Trade & Services"},
    {"sic": 7380, "industry": "SERVICES-MISCELLANEOUS BUSINESS SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7381, "industry": "SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7384, "industry": "SERVICES-PHOTOFINISHING LABORATORIES", "office": "Office of Trade & Services"},
    {"sic": 7385, "industry": "SERVICES-TELEPHONE INTERCONNECT SYSTEMS", "office": "Office of Trade & Services"},
    {"sic": 7389, "industry": "SERVICES-BUSINESS SERVICES, NEC", "office": "Office of Trade & Services or Office of Energy & Transportation"},
    {"sic": 7500, "industry": "SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING", "office": "Office of Trade & Services"},
    {"sic": 7510, "industry": "SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)", "office": "Office of Trade & Services"},
    {"sic": 7600, "industry": "SERVICES-MISCELLANEOUS REPAIR SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7812, "industry": "SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION", "office": "Office of Trade & Services"},
    {"sic": 7819, "industry": "SERVICES-ALLIED TO MOTION PICTURE PRODUCTION", "office": "Office of Trade & Services"},
    {"sic": 7822, "industry": "SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION", "office": "Office of Trade & Services"},
    {"sic": 7829, "industry": "SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION", "office": "Office of Trade & Services"},
    {"sic": 7830, "industry": "SERVICES-MOTION PICTURE THEATERS", "office": "Office of Trade & Services"},
    {"sic": 7841, "industry": "SERVICES-VIDEO TAPE RENTAL", "office": "Office of Trade & Services"},
    {"sic": 7900, "industry": "SERVICES-AMUSEMENT & RECREATION SERVICES", "office": "Office of Trade & Services"},
    {"sic": 7948, "industry": "SERVICES-RACING, INCLUDING TRACK OPERATION", "office": "Office of Trade & Services"},
    {"sic": 7990, "industry": "SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION", "office": "Office of Trade & Services"},
    {"sic": 7997, "industry": "SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS", "office": "Office of Trade & Services"},
    {"sic": 8000, "industry": "SERVICES-HEALTH SERVICES", "office": "Industrial Applications and Services"},
    {"sic": 8011, "industry": "SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE", "office": "Industrial Applications and Services"},
    {"sic": 8050, "industry": "SERVICES-NURSING & PERSONAL CARE FACILITIES", "office": "Industrial Applications and Services"},
    {"sic": 8051, "industry": "SERVICES-SKILLED NURSING CARE FACILITIES", "office": "Industrial Applications and Services"},
    {"sic": 8060, "industry": "SERVICES-HOSPITALS", "office": "Industrial Applications and Services"},
    {"sic": 8062, "industry": "SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC", "office": "Industrial Applications and Services"},
    {"sic": 8071, "industry": "SERVICES-MEDICAL LABORATORIES", "office": "Industrial Applications and Services"},
    {"sic": 8082, "industry": "SERVICES-HOME HEALTH CARE SERVICES", "office": "Industrial Applications and Services"},
    {"sic": 8090, "industry": "SERVICES-MISC HEALTH & ALLIED SERVICES, NEC", "office": "Industrial Applications and Services"},
    {"sic": 8093, "industry": "SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC", "office": "Industrial Applications and Services"},
    {"sic": 8111, "industry": "SERVICES-LEGAL SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8200, "industry": "SERVICES-EDUCATIONAL SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8300, "industry": "SERVICES-SOCIAL SERVICES", "office": "Industrial Applications and Services"},
    {"sic": 8351, "industry": "SERVICES-CHILD DAY CARE SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8600, "industry": "SERVICES-MEMBERSHIP ORGANIZATIONS", "office": "Office of Trade & Services"},
    {"sic": 8700, "industry": "SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT", "office": "Office of Trade & Services"},
    {"sic": 8711, "industry": "SERVICES-ENGINEERING SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8731, "industry": "SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH", "office": "Industrial Applications and Services"},
    {"sic": 8734, "industry": "SERVICES-TESTING LABORATORIES", "office": "Industrial Applications and Services"},
    {"sic": 8741, "industry": "SERVICES-MANAGEMENT SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8742, "industry": "SERVICES-MANAGEMENT CONSULTING SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8744, "industry": "SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES", "office": "Office of Trade & Services"},
    {"sic": 8880, "industry": "AMERICAN DEPOSITARY RECEIPTS", "office": "Office of International Corp Fin"},
    {"sic": 8888, "industry": "FOREIGN GOVERNMENTS", "office": "Office of International Corp Fin"},
    {"sic": 8900, "industry": "SERVICES-SERVICES, NEC", "office": "Office of Trade & Services"},
    {"sic": 9721, "industry": "INTERNATIONAL AFFAIRS", "office": "Office of International Corp Fin"},
    {"sic": 9995, "industry": "NON-OPERATING ESTABLISHMENTS", "office": "Office of Real Estate & Construction"},
]
